// ============================================================
// Mock product data — replace with real API/database calls
// ============================================================
import type { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "golden-glow-self-tanner",
    name: "Golden Glow Self Tanner",
    shortDescription: "Streak-free, buildable bronze that lasts up to 7 days.",
    description:
      "Achieve a natural, sun-kissed glow from the comfort of your home with our award-winning Golden Glow Self Tanner. Infused with nourishing argan oil and hyaluronic acid, this ultra-smooth formula glides on effortlessly for an even, streak-free finish. The subtle coconut fragrance masks the typical self-tanner scent while deeply hydrating your skin. Buildable color adapts to all skin tones.",
    price: 49.99,
    compareAtPrice: 69.99,
    currency: "USD",
    images: [
      {
        id: "img-1-1",
        url: "/placeholder/product-1.jpg",
        alt: "Golden Glow Self Tanner bottle",
        width: 800,
        height: 800,
        isPrimary: true,
      },
      {
        id: "img-1-2",
        url: "/placeholder/product-1-2.jpg",
        alt: "Golden Glow Self Tanner texture",
        width: 800,
        height: 800,
        isPrimary: false,
      },
    ],
    category: "self-tanner",
    tags: ["bestseller", "streak-free", "hydrating", "vegan"],
    rating: 4.8,
    reviewCount: 1247,
    stockStatus: "in_stock",
    stockCount: 42,
    sku: "LT-ST-001",
    isFeatured: true,
    isNew: false,
    discount: 28,
    specifications: [
      { label: "Volume", value: "150ml" },
      { label: "Skin Type", value: "All skin types" },
      { label: "Scent", value: "Tropical Coconut" },
      { label: "DHA Concentration", value: "5-8%" },
      { label: "Duration", value: "5-7 days" },
      { label: "Vegan", value: "Yes" },
      { label: "Cruelty-Free", value: "Yes" },
    ],
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "2",
    slug: "luxe-bronzing-mousse",
    name: "Luxe Bronzing Mousse",
    shortDescription: "Ultra-light mousse for an instant luminous glow.",
    description:
      "Our feather-light bronzing mousse delivers a deep, radiant tan that looks and feels completely natural. The revolutionary aerated formula absorbs instantly with zero transfer — leaving no orange tones, just gorgeous, long-lasting bronze. Perfect for face and body.",
    price: 39.99,
    compareAtPrice: 55.00,
    currency: "USD",
    images: [
      {
        id: "img-2-1",
        url: "/placeholder/product-2.jpg",
        alt: "Luxe Bronzing Mousse",
        width: 800,
        height: 800,
        isPrimary: true,
      },
    ],
    category: "bronzer",
    tags: ["mousse", "fast-drying", "no-transfer", "natural"],
    rating: 4.6,
    reviewCount: 892,
    stockStatus: "in_stock",
    stockCount: 28,
    sku: "LT-BR-002",
    isFeatured: true,
    isNew: true,
    discount: 27,
    specifications: [
      { label: "Volume", value: "200ml" },
      { label: "Application", value: "Tanning mitt recommended" },
      { label: "Dry Time", value: "60 seconds" },
      { label: "Duration", value: "7-10 days" },
      { label: "Finish", value: "Radiant / Luminous" },
      { label: "Paraben-Free", value: "Yes" },
    ],
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-06-05T00:00:00Z",
  },
  {
    id: "3",
    slug: "sun-kissed-tanning-oil",
    name: "Sun-Kissed Tanning Oil",
    shortDescription: "Rich tanning oil with SPF 15 protection.",
    description:
      "Bask in the sun with our luxurious Tanning Oil, formulated with a blend of exotic oils — avocado, macadamia, and jojoba — to accelerate your natural tan while keeping skin intensely moisturised. The lightweight formula absorbs beautifully, giving skin a gorgeous bronzed sheen.",
    price: 34.99,
    compareAtPrice: undefined,
    currency: "USD",
    images: [
      {
        id: "img-3-1",
        url: "/placeholder/product-3.jpg",
        alt: "Sun-Kissed Tanning Oil",
        width: 800,
        height: 800,
        isPrimary: true,
      },
    ],
    category: "tanning-lotion",
    tags: ["oil", "spf", "moisturising", "natural"],
    rating: 4.5,
    reviewCount: 634,
    stockStatus: "in_stock",
    stockCount: 19,
    sku: "LT-OL-003",
    isFeatured: false,
    isNew: false,
    specifications: [
      { label: "Volume", value: "100ml" },
      { label: "SPF", value: "SPF 15" },
      { label: "Key Ingredients", value: "Avocado, Macadamia, Jojoba" },
      { label: "Skin Type", value: "Dry to Normal" },
      { label: "Water-Resistant", value: "80 minutes" },
    ],
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-05-15T00:00:00Z",
  },
  {
    id: "4",
    slug: "overnight-tan-drops",
    name: "Overnight Tan Drops",
    shortDescription: "Concentrated drops that work while you sleep.",
    description:
      "Wake up to a radiant, golden glow with our powerful overnight tan drops. Mix a few drops with your favourite moisturiser and apply before bed for a natural-looking tan by morning. Suitable for all skin tones — simply adjust the number of drops to control your colour intensity.",
    price: 44.99,
    compareAtPrice: 59.99,
    currency: "USD",
    images: [
      {
        id: "img-4-1",
        url: "/placeholder/product-4.jpg",
        alt: "Overnight Tan Drops",
        width: 800,
        height: 800,
        isPrimary: true,
      },
    ],
    category: "self-tanner",
    tags: ["drops", "overnight", "buildable", "customisable"],
    rating: 4.7,
    reviewCount: 1083,
    stockStatus: "low_stock",
    stockCount: 4,
    sku: "LT-DR-004",
    isFeatured: true,
    isNew: false,
    discount: 25,
    specifications: [
      { label: "Volume", value: "30ml (dropper bottle)" },
      { label: "Usage", value: "Mix 2–10 drops with moisturiser" },
      { label: "Result Time", value: "6-8 hours" },
      { label: "Duration", value: "5-7 days" },
      { label: "Fragrance", value: "Fragrance-Free" },
      { label: "Suitable For", value: "Face & Body" },
    ],
    createdAt: "2024-04-20T00:00:00Z",
    updatedAt: "2024-06-10T00:00:00Z",
  },
  {
    id: "5",
    slug: "after-sun-recovery-lotion",
    name: "After Sun Recovery Lotion",
    shortDescription: "Soothe, hydrate and extend your tan.",
    description:
      "Rescue sun-stressed skin with our intensely nourishing After Sun Recovery Lotion. Packed with aloe vera, vitamin E and hyaluronic acid, it instantly cools and soothes while locking in moisture for lasting softness. The tan-extending formula ensures your colour stays vivid for longer.",
    price: 29.99,
    compareAtPrice: undefined,
    currency: "USD",
    images: [
      {
        id: "img-5-1",
        url: "/placeholder/product-5.jpg",
        alt: "After Sun Recovery Lotion",
        width: 800,
        height: 800,
        isPrimary: true,
      },
    ],
    category: "after-sun",
    tags: ["aloe", "soothing", "hydrating", "tan-extending"],
    rating: 4.9,
    reviewCount: 756,
    stockStatus: "in_stock",
    stockCount: 55,
    sku: "LT-AS-005",
    isFeatured: false,
    isNew: true,
    specifications: [
      { label: "Volume", value: "250ml" },
      { label: "Key Ingredients", value: "Aloe Vera, Vitamin E, Hyaluronic Acid" },
      { label: "Skin Type", value: "All skin types" },
      { label: "Texture", value: "Light Lotion" },
      { label: "Alcohol-Free", value: "Yes" },
    ],
    createdAt: "2024-05-01T00:00:00Z",
    updatedAt: "2024-06-08T00:00:00Z",
  },
  {
    id: "6",
    slug: "tanning-starter-kit",
    name: "Tanning Starter Kit",
    shortDescription: "Everything you need for the perfect tan — bundled.",
    description:
      "The ultimate tanning kit for beginners and pros alike. Includes our Golden Glow Self Tanner, a professional tanning mitt, an exfoliating glove, and our After Sun Lotion — everything you need for a flawless, long-lasting tan from first application.",
    price: 89.99,
    compareAtPrice: 134.97,
    currency: "USD",
    images: [
      {
        id: "img-6-1",
        url: "/placeholder/product-6.jpg",
        alt: "Tanning Starter Kit",
        width: 800,
        height: 800,
        isPrimary: true,
      },
    ],
    category: "bundles",
    tags: ["bundle", "starter", "value", "gift"],
    rating: 4.8,
    reviewCount: 421,
    stockStatus: "in_stock",
    stockCount: 15,
    sku: "LT-BU-006",
    isFeatured: true,
    isNew: false,
    discount: 33,
    specifications: [
      { label: "Includes", value: "Self Tanner 150ml, Tanning Mitt, Exfoliating Glove, After Sun 100ml" },
      { label: "Value", value: "Save 33%" },
      { label: "Packaging", value: "Premium gift box" },
    ],
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2024-06-12T00:00:00Z",
  },
  {
    id: "7",
    slug: "face-tanning-serum",
    name: "Face Tanning Serum",
    shortDescription: "Anti-aging tanning serum for a youthful, radiant complexion.",
    description:
      "Our premium face-specific tanning serum combines active tanning technology with powerful anti-aging peptides and vitamin C. The lightweight formula develops into a natural, golden glow over 8 hours while visibly reducing fine lines and unifying skin tone. Dermatologist tested.",
    price: 55.99,
    compareAtPrice: 79.99,
    currency: "USD",
    images: [
      {
        id: "img-7-1",
        url: "/placeholder/product-7.jpg",
        alt: "Face Tanning Serum",
        width: 800,
        height: 800,
        isPrimary: true,
      },
    ],
    category: "self-tanner",
    tags: ["face", "anti-aging", "serum", "vitamin-c", "premium"],
    rating: 4.7,
    reviewCount: 598,
    stockStatus: "in_stock",
    stockCount: 30,
    sku: "LT-FS-007",
    isFeatured: false,
    isNew: true,
    discount: 30,
    specifications: [
      { label: "Volume", value: "30ml" },
      { label: "Key Ingredients", value: "DHA, Vitamin C, Peptides, Niacinamide" },
      { label: "Suitable For", value: "Face only" },
      { label: "Dermatologist Tested", value: "Yes" },
      { label: "Fragrance-Free", value: "Yes" },
    ],
    createdAt: "2024-05-15T00:00:00Z",
    updatedAt: "2024-06-15T00:00:00Z",
  },
  {
    id: "8",
    slug: "professional-tanning-mitt",
    name: "Professional Tanning Mitt",
    shortDescription: "Velvet-soft mitt for a streak-free application.",
    description:
      "Achieve salon-quality results at home with our professional-grade tanning mitt. The ultra-smooth velvet surface ensures even, streak-free application every time, while the waterproof backing protects your palms from staining. Machine washable and reusable.",
    price: 14.99,
    compareAtPrice: undefined,
    currency: "USD",
    images: [
      {
        id: "img-8-1",
        url: "/placeholder/product-8.jpg",
        alt: "Professional Tanning Mitt",
        width: 800,
        height: 800,
        isPrimary: true,
      },
    ],
    category: "accessories",
    tags: ["mitt", "accessory", "streak-free", "reusable"],
    rating: 4.6,
    reviewCount: 2134,
    stockStatus: "in_stock",
    stockCount: 120,
    sku: "LT-AC-008",
    isFeatured: false,
    isNew: false,
    specifications: [
      { label: "Material", value: "Microfibre velvet" },
      { label: "Backing", value: "Waterproof" },
      { label: "Washing", value: "Machine washable" },
      { label: "Fits", value: "One size fits all" },
    ],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-04-01T00:00:00Z",
  },
];

export const FAQ_ITEMS = [
  {
    id: "faq-1",
    question: "How long does the tan last?",
    answer:
      "Our self-tanners typically last between 5 to 10 days depending on the product and your skin type. To maximise longevity, moisturise daily and avoid long hot baths or showers. Use our After Sun Recovery Lotion to extend your colour.",
  },
  {
    id: "faq-2",
    question: "Will it turn me orange?",
    answer:
      "Absolutely not! Our formulas are carefully developed to deliver natural-looking, golden bronze tones across all skin types. We use premium DHA combined with colour guides to ensure the most realistic results.",
  },
  {
    id: "faq-3",
    question: "How should I prepare my skin?",
    answer:
      "For the best results, exfoliate your skin 24 hours before application using our Exfoliating Glove, paying extra attention to dry areas like knees, elbows, and ankles. Shower, dry off completely, and apply your chosen product. Avoid moisturising immediately before application.",
  },
  {
    id: "faq-4",
    question: "Are your products vegan and cruelty-free?",
    answer:
      "Yes! All Luxe Tan products are 100% vegan and cruelty-free. We never test on animals and use only ethically sourced, plant-based ingredients wherever possible. Our products are also free from parabens and harsh sulphates.",
  },
  {
    id: "faq-5",
    question: "How quickly will my order arrive?",
    answer:
      "Standard shipping takes 3-5 business days. Express shipping (1-2 business days) is available at checkout. Orders over $75 qualify for free standard shipping. You'll receive a tracking number as soon as your order ships.",
  },
  {
    id: "faq-6",
    question: "Can I use self-tanner on my face?",
    answer:
      "Yes! We recommend our Face Tanning Serum which is specifically formulated for facial skin. It's non-comedogenic, fragrance-free, and contains additional skin-care actives. For body products on the face, always do a patch test first.",
  },
  {
    id: "faq-7",
    question: "What is your return policy?",
    answer:
      "We offer a 30-day satisfaction guarantee. If you're not happy with your purchase for any reason, contact our customer service team and we'll arrange a full refund or exchange. Products must be returned in their original packaging.",
  },
];
